version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: laravel_app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql/mysql-server:5.7
    platform: linux/amd64
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.conf:/etc/mysql/conf.d/my.conf
      # - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - larabel_db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=laravel_db
      - PMA_USER=root
      - PMA_PASSWORD=root
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
    ports:
      - "8081:80"
