version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html

  db:
    platform: linux/amd64
    image: mysql:5.7
    container_name: laravel_db
    environment:
    # rootとuserのパスワードなどを同じものにしてはいけない
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.conf:/etc/mysql/conf.d/my.conf
      # - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    command: mysqld --innodb_use_native_aio=0

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=admin
      - PMA_PASSWORD=password
    ports:
      - "8080:80"
    volumes:
      - ./phpmyadmin/sessions:/sessions
